<a href="https://colab.research.google.com/github/Guhan2348519/QC_LAB/blob/main/2348519_QC_LAB3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
!pip install qiskit
!pip install qiskit_aer

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.8/4.8 MB 30.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 119.4/119.4 kB 8.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 49.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.7/49.7 kB 3.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.7/49.7 MB 11.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 108.5/108.5 kB 8.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.3/12.3 MB 80.5 MB/s eta 0:00:00


In [4]:
from qiskit.quantum_info import Statevector, Operator
from numpy import sqrt
import numpy as np

In [5]:
zero,one=Statevector.from_label("0"), Statevector.from_label("1")

In [6]:
zero.tensor(one).draw("latex")

<IPython.core.display.Latex object>

In [7]:
plus=Statevector.from_label("+")

In [8]:
i_state = Statevector([1/sqrt(2), 1j/sqrt(2)])

psi=plus.tensor(i_state)

In [9]:
psi.draw("latex")

<IPython.core.display.Latex object>

In [10]:
X = Operator([[0, 1], [1, 0]])
I=Operator([[1, 0],[0, 1]])

In [11]:
X. tensor(I)

Operator([[0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j],
          [0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j],
          [1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
          [0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j]],
         input_dims=(2, 2), output_dims=(2, 2))


In [12]:
psi.evolve(I ^ X). draw("latex")

<IPython.core.display.Latex object>

In [13]:
CX=Operator(
[
[1, 0, 0, 0],
[0, 1, 0, 0],
[0, 0, 0, 1],
[0, 0, 1, 0],
]
)

In [14]:
psi.evolve (CX).draw("latex")

<IPython.core.display.Latex object>

In [47]:
result, new_sv=Measure([8])
print("Measured: (result)\nState aftor censureent new sv.drawLatex")

NameError: name 'Measure' is not defined

In [17]:
W=Statevector([0, 1, 1, 0, 1, 0, 0, 0]/ sqrt(3))

W.draw("latex")

<IPython.core.display.Latex object>

Toffoli operation and represented im dirac notation

In [42]:
!pip install pylatexenc
!pip install matplotlib
!pip install qiskit_aer
from qiskit import QuantumCircuit, QuantumRegister, ClassicalRegister
from qiskit.quantum_info import Statevector
import numpy as np
from qiskit_aer import AerSimulator
from IPython.display import display  # Import display

In [43]:
qc = QuantumCircuit(3, 3)
qc.initialize([1, 0], 0)
qc.initialize([0, 1], 1)
qc.initialize([1/np.sqrt(2), 1/np.sqrt(2)], 2)
qc.ccx(0, 1, 2)


display(qc.draw(output='text'))
simulator = AerSimulator()
qc.save_statevector()
result = simulator.run(qc).result()
statevector = result.get_statevector()
print(statevector)

┌─────────────────┐           
q_0: ──────┤ Initialize(1,0) ├────────■──
           ├─────────────────┤        │  
q_1: ──────┤ Initialize(0,1) ├────────■──
     ┌─────┴─────────────────┴─────┐┌─┴─┐
q_2: ┤ Initialize(0.70711,0.70711) ├┤ X ├
     └─────────────────────────────┘└───┘
c: 3/════════════════════════════════════

Statevector([0.        +0.j, 0.        +0.j, 0.70710678+0.j,
             0.        +0.j, 0.        +0.j, 0.        +0.j,
             0.70710678+0.j, 0.        +0.j],
            dims=(2, 2, 2))


In [46]:
from qiskit.visualization import state_visualization
# Convert the statevector to LaTeX representation in Dirac notation
latex_representation = state_visualization.array_to_latex(statevector, prefix="|\\psi\\rangle =")
# Display the LaTeX representation
display(latex_representation)

<IPython.core.display.Latex object>

In [55]:
# Define the Toffoli gate matrix
toffoli_matrix = np.array([[1, 0, 0, 0, 0, 0, 0, 0],
                           [0, 1, 0, 0, 0, 0, 0, 0],
                           [0, 0, 1, 0, 0, 0, 0, 0],
                           [0, 0, 0, 1, 0, 0, 0, 0],
                           [0, 0, 0, 0, 1, 0, 0, 0],
                           [0, 0, 0, 0, 0, 1, 0, 0],
                           [0, 0, 0, 0, 0, 0, 0, 1],
                           [0, 0, 0, 0, 0, 0, 1, 0]])

# Print the matrix
print(toffoli_matrix)

# Dirac notation
print("\nDirac Notation:")
print("|a, b, c⟩ -> |a, b, c ⊕ (a ∧ b)⟩")

[[1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]]

Dirac Notation:
|a, b, c⟩ -> |a, b, c ⊕ (a ∧ b)⟩


CSWAP operatiop with dirac notation

In [54]:
from qiskit import QuantumCircuit
import matplotlib as plt
qc = QuantumCircuit(3)
qc.cswap(0, 1, 2)
display(qc.draw(output='text'))
# Get the unitary matrix representation of the CSWAP gate
cswap_matrix = Operator(qc).data
print("\nMatrix Representation of CSWAP Gate:")
print(cswap_matrix)
# Dirac notation representation
print("\nDirac Notation:")
print("|a, b, c⟩ -> |a, b⊕a(b⊕c), c⊕a(b⊕c)⟩")

q_0: ─■─
      │ 
q_1: ─X─
      │ 
q_2: ─X─


Matrix Representation of CSWAP Gate:
[[1.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 1.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 1.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 1.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 1.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 1.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 1.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 1.+0.j]]

Dirac Notation:
|a, b, c⟩ -> |a, b⊕a(b⊕c), c⊕a(b⊕c)⟩


In [49]:
import numpy as np
import matplotlib.pyplot as plt
# Define the quantum states
zero = np.array([1, 0])
one = np.array([0, 1])
plus = (1/np.sqrt(2)) * np.array([1, 1])
# Initialize qubits
q0 = zero
q1 = one
q2 = plus
# Define the controlled swap (Fredkin) gate
def cswap(control, target1, target2):
  if np.array_equal(control, one):
   return target2, target1
  else:
   return target1, target2
# Apply controlled swap gate
q1, q2 = cswap(q0, q1, q2)
# Display the results
print(f"Qubit 0 state: {q0}")
print(f"Qubit 1 state: {q1}")
print(f"Qubit 2 state: {q2}")

Qubit 0 state: [1 0]
Qubit 1 state: [0 1]
Qubit 2 state: [0.70710678 0.70710678]
